spring:
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: ${APP_PROFILE:dev}

cliente:
  validador:
    url: https://www.4devs.com.br/ferramentas_online.php
