spring:
  datasource:
    driverClassName: org.postgresql.Driver
    name: assembleiadb
    password: ${PASSWORD_DB:postgres}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${USER_DB:postgres}
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: ${STACKHERO_RABBITMQ_HOST:localhost}
    listener:
      simple:
        default-requeue-rejected: false
    password: ${STACKHERO_RABBITMQ_PASSWORD:admin}
    port: ${RABBIT_PORT:5672}
    username: ${STACKHERO_RABBITMQ_USER:admin}
    virtual-host: ${RABBIT_VHOST:/}
